### PR TITLE
Port module to Drupal 8

### PR DESCRIPTION
**Pull request by kasperg**
### Description ###

This is a followup on #4  which replaces existing Drupal 7 files with the corresponding Drupal 8 versions.

Main `SystemSetQueue` class is replaced with a corresponding `UniqueDatabaseQueue` class.

The new class uses the same approach as the Drupal 7 version by extending the existing schema with a new `md5` field with an unique key and interpreting exceptions to be an indication of an existing item.

The MD5 checksum is calculated using PHP because it is simpler (and potentially more portable) when using the Drupal 8 database API.

The implementation is reduced a lot simpler by inheriting more of the methods from the parent `DatabaseQueue` class.

Dependency on `registry_autoload` is dropped as the module is obsolete for Drupal 8.

Update `README` accordingly. References to Queue UI have been dropped for now as there are no patches for the Drupal 8 version which can add support for this module.

### Thoughts/questions/comments ###

This is intentionally a pretty straight port of the approach taken by the Drupal 7 module. 

Specific exeception classes in Drupal 8 make it easier to limit which database exceptions are interpreted as duplicate entries - `IntegrityConstraintViolationException` is a lot better than `PDOException`. However I have been thinking about whether it is enough. Other situations might cause the same issue. Another option would be to use a [`Merge` query](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Database%21Query%21Merge.php/class/Merge/8.2.x) which does not touch any fields for updates. This would make the module more in line with [`fourkitchens/upsert_queue`](https://github.com/fourkitchens/upsert_queue/).

As mentioned I dropped support for Queue UI. However [a recent change to Queue UI has added support for custom backends](https://www.drupal.org/node/2944670). We could build on that if we want to keep this support.

I implemented a test for the module in the process but there is not any infrastructure for running here. I do not know if it is worth keeping it around.

### CODE REVIEW

**Comment by e0ipso** [comment]
> We could build on that if we want to keep this support.

That'd be great! Can you create a follow up for that?

**Comment by e0ipso** [comment]
> I implemented a test for the module in the process but there is not any infrastructure for running here. I do not know if it is worth keeping it around.

Totally worth it. We should create a Travis CI or Circle CI integration to run them. Can you create a follow up ticket for that as well?

**Comment by e0ipso** [comment]
@kasperg would you like to be become a collaborator in this GitHub repo? I'd love to give you more autonomy in merging and creating things, if that's something you'd like.

**Comment by kasperg** [comment]
I have created issues for Queue UI support #6 and continuous integration pipeline #7.

I do not mind becoming collaborator but do not expect too much from me. I like the simplicity of the module as it is 😄 .

**Comment by e0ipso** [comment]
This looks great! There are some minor issues that can be fixed on follow ups.

**Pull request merged**
